In [4]:
import pandas as pd
import numpy as np

data = pd.read_csv(r'C:\Users\Swastik Bhatnagar\Desktop\raw_data_unprocessed.csv')

data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 28 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Unnamed: 0                         103904 non-null  int64
 1   id                                 103904 non-null  int64
 2   Gender                             103904 non-null  int64
 3   Customer Type                      103904 non-null  int64
 4   Age                                103904 non-null  int64
 5   Flight Distance                    103904 non-null  int64
 6   Inflight wifi service              103904 non-null  int64
 7   Departure/Arrival time convenient  103904 non-null  int64
 8   Ease of Online booking             103904 non-null  int64
 9   Gate location                      103904 non-null  int64
 10  Food and drink                     103904 non-null  int64
 11  Online boarding                    103904 non-null  int64
 12  Seat comfort                       103904 non-null  int64
 13  Inflight entertainment             103904 non-null  int64
 14  On-board service                   103904 non-null  int64
 15  Leg room service                   103904 non-null  int64
 16  Baggage handling                   103904 non-null  int64
 17  Checkin service                    103904 non-null  int64
 18  Inflight service                   103904 non-null  int64
 19  Cleanliness                        103904 non-null  int64
 20  Departure Delay in Minutes         103904 non-null  int64
 21  Arrival Delay in Minutes           103594 non-null  float64
 22  satisfaction                       103904 non-null  int64
 23  Business                           103904 non-null  int64
 24  Eco                                103904 non-null  int64
 25  Eco Plus                           103904 non-null  int64
 26  Business travel                    103904 non-null  int64
 27  Personal Travel                    103904 non-null  int64
dtypes: float64(1), int64(27)
memory usage: 22.2 MB

,Unnamed: 0,id,Gender,Customer Type,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,Business,Eco,Eco Plus,Business travel,Personal Travel
0,0,70172,1,1,13,460,3,4,3,1,...,5,5,25,18.0,0,0,0,1,0,1
1,1,5047,1,0,25,235,3,2,3,3,...,4,1,1,6.0,0,1,0,0,1,0
2,2,110028,0,1,26,1142,2,2,2,2,...,4,5,0,0.0,1,1,0,0,1,0
3,3,24026,0,1,25,562,2,5,5,5,...,4,2,11,9.0,0,1,0,0,1,0
4,4,119299,1,1,61,214,3,3,3,3,...,3,3,0,0.0,1,1,0,0,1,0

In [12]:
# Dropping unnecessary columns
data_cleaned = data.drop(columns=['Unnamed: 0', 'id'])

In [13]:
# Handling missing values for 'Arrival Delay in Minutes'
data_cleaned['Arrival Delay in Minutes'].fillna(data_cleaned['Arrival Delay in Minutes'].median(), inplace=True)

In [15]:
data_cleaned.head()

,Gender,Customer Type,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,...,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,Business,Eco,Eco Plus,Business travel,Personal Travel
0,1,1,13,460,3,4,3,1,5,3,...,5,5,25,18.0,0,0,0,1,0,1
1,1,0,25,235,3,2,3,3,1,3,...,4,1,1,6.0,0,1,0,0,1,0
2,0,1,26,1142,2,2,2,2,5,5,...,4,5,0,0.0,1,1,0,0,1,0
3,0,1,25,562,2,5,5,5,2,2,...,4,2,11,9.0,0,1,0,0,1,0
4,1,1,61,214,3,3,3,3,4,5,...,3,3,0,0.0,1,1,0,0,1,0

In [9]:
from sklearn.model_selection import train_test_split

# Splitting the data into features and target variable
X = data_cleaned.drop('satisfaction', axis=1)
y = data_cleaned['satisfaction']

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.ensemble import RandomForestClassifier

# Initializing the Random Forest classifier
rf_clf = RandomForestClassifier(random_state=42)

# Fitting the model to the training data
rf_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [11]:
from sklearn.metrics import accuracy_score

# Predicting the target values for the test set
y_pred = rf_clf.predict(X_test)

# Calculating and printing the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy:.4f}")

Model accuracy: 0.9636